# Generated by Django 2.2.4 on 2019-09-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190925_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Data'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
