# Generated by Django 2.2.4 on 2019-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190925_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conclusion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='editors_note',
            field=models.CharField(help_text='Please keep Max=64_Char', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='para_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='para_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='para_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
