# Generated by Django 2.2.4 on 2019-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190925_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_art',
            field=models.ImageField(blank=True, help_text='Please Include an image (*.png, *.jpeg', upload_to='Covers/'),
        ),
    ]
