# Generated by Django 2.2.4 on 2019-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_source',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
