# Generated by Django 2.2.4 on 2019-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_art_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_1',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_2',
            field=models.CharField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_3',
            field=models.CharField(max_length=750, null=True),
        ),
    ]
