# Generated by Django 2.2.4 on 2019-10-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190925_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='conclusion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_art',
            field=models.ImageField(blank=True, default='default.png', help_text='Please Include an image (*.png, *.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_1',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_2',
            field=models.TextField(max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_3',
            field=models.TextField(max_length=750, null=True),
        ),
    ]
