# Generated by Django 2.2.4 on 2019-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191004_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='para_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='conclusion',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_1',
            field=models.TextField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_2',
            field=models.TextField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='para_3',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
